services:
  postgres:
    container_name: postgress_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: my-secret-pw
      POSTGRES_DB: identity_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_postgres_identity_client
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5051:81"
    restart: unless-stopped

volumes:
  postgres:
  pgadmin: