spring:
  application:
    name: identity-service
  datasource:
    password: my-secret-pw
    url: jdbc:postgresql://localhost:5433/identity_db
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
server:
  port: 8081
